# Generated by Django 2.2.5 on 2019-10-09 11:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_auto_20191008_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='cuerpo',
            field=tinymce.models.HTMLField(),
        ),
    ]
